name: CI

on: [push, pull_request]

jobs:
  format:
    name: Check formatting
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - name: Install uv
        uses: astral-sh/setup-uv@ba17a16c0afc72ea47311891c76009518d0cf1aa
        with:
          version: "0.11.8"

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version-file: ".python-version"

      - name: Run black
        run: uv tool run black --check --verbose */**/src */**/test

  typecheck:
    name: Type Check
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - name: Install uv
        uses: astral-sh/setup-uv@ba17a16c0afc72ea47311891c76009518d0cf1aa
        with:
          version: "0.11.8"

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version-file: ".python-version"

      - name: Run mypy
        run: uv tool run mypy

  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - name: Install uv
        uses: astral-sh/setup-uv@ba17a16c0afc72ea47311891c76009518d0cf1aa
        with:
          version: "0.11.8"

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version-file: ".python-version"

      - name: Run Ruff
        run: uv tool run ruff check --output-format=github .

  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - name: Install uv
        uses: astral-sh/setup-uv@ba17a16c0afc72ea47311891c76009518d0cf1aa
        with:
          version: "0.11.8"

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version-file: ".python-version"

      - name: Install the project
        run: uv sync --locked --all-extras --dev --all-packages

      - name: Run tests
        run: uv run pytest